server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    discovery:
      client:
        simple:
          instances:
            seat-service:
              - uri: http://localhost:8083
            auth-service:
              - uri: http://localhost:8081
            flight-service:
              - uri: http://localhost:8082
            booking-service:
              - uri: http://localhost:8084
            payment-service:
              - uri: http://localhost:8085
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

app:
  auth:
    tokenSecret: ${TOKEN_SECRET:9a4f2c8d3b7a1e5f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1d}

eureka:
  client:
    enabled: false
