server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  #    register-with-eureka: true
  #    fetch-registry: true
  instance:
    hostname: api-gateway
    prefer-ip-address: true

  # cloud:
  #   gateway:
  #     routes:
  #       - id: auth-service
  #         uri: lb://auth-service
  #         predicates:
  #           - Path=/api/v1/auth/**
  #         filters:
  #           - name: RequestRateLimiter
  #             args:
  #               redis-rate-limiter.replenishRate: 10
  #               redis-rate-limiter.burstCapacity: 20
  #               key-resolver: "#{@userKeyResolver}"

  #       - id: flight-service
  #         uri: lb://flight-service
  #         predicates:
  #           - Path=/api/v1/flights/**
  #         filters:
  #           - AuthFilter
  #           - name: RequestRateLimiter
  #             args:
  #               redis-rate-limiter.replenishRate: 5
  #               redis-rate-limiter.burstCapacity: 10
  #               key-resolver: "#{@userKeyResolver}"

  #       - id: booking-service
  #         uri: lb://booking-service
  #         predicates:
  #           - Path=/api/v1/bookings/**
  #         filters:
  #           - AuthFilter
  #           - name: RequestRateLimiter
  #             args:
  #               redis-rate-limiter.replenishRate: 2
  #               redis-rate-limiter.burstCapacity: 5
  #               key-resolver: "#{@userKeyResolver}"

  #       - id: account-service
  #         uri: lb://account-service
  #         predicates:
  #           - Path=/api/v1/accounts/**
  #         filters:
  #           - AuthFilter

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

app:
  auth:
    tokenSecret: ${TOKEN_SECRET}