# Sử dụng image cơ sở Java
FROM eclipse-temurin:21-jdk

# Thông tin tác giả
LABEL authors="pdlong4002"

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép tệp JAR vào container
COPY target/payment-service-0.0.1-SNAPSHOT.jar payment-service-0.0.1-SNAPSHOT.jar

# Expose port của ứng dụng
EXPOSE 8085

# Câu lệnh để chạy ứng dụng
ENTRYPOINT ["java", "-jar", "payment-service-0.0.1-SNAPSHOT.jar"]