# Sử dụng image cơ sở Java
FROM eclipse-temurin:21-jdk

# Thông tin tác giả
LABEL authors="pdlong4002"

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép tệp JAR vào container
COPY target/booking-service-0.0.1-SNAPSHOT.jar booking-service-0.0.1-SNAPSHOT.jar

# Expose port của ứng dụng
EXPOSE 8084

# Câu lệnh để chạy ứng dụng
ENTRYPOINT ["java", "-jar", "booking-service-0.0.1-SNAPSHOT.jar"]