name: CI API Gateway

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'api-gateway/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'api-gateway/**'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-template.yml
    with:
      service-name: api-gateway
      service-dir: api-gateway
