name: CI Config Service

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'config-service/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'config-service/**'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-template.yml
    with:
      service-name: config-service
      service-dir: config-service
