name: CI Flight Service

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'flight-service/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'flight-service/**'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-template.yml
    with:
      service-name: flight-service
      service-dir: flight-service
