name: CI Payment Service

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'payment-service/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'payment-service/**'

jobs:
  trigger-build:
    uses: ./.github/workflows/build-template.yml
    with:
      service-name: payment-service
      service-dir: payment-service
